name: Docker Image CI

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - run: docker build . --file Dockerfile --tag braintrap:${GITHUB_REF#refs/heads/}
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@v1.1.2
      with:
        name: virtualflybrain/braintrap
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
