name: Docker Image CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Get safe branch name
      id: branch-name
      run: |
        SAFE_BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
        echo "branch=$SAFE_BRANCH_NAME" >> $GITHUB_OUTPUT
        
    - name: Build Docker image 
      run: docker build . --file Dockerfile --tag braintrap:${{ steps.branch-name.outputs.branch }}
      
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@v1.1.2
      with:
        name: virtualflybrain/braintrap
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        tag: ${{ steps.branch-name.outputs.branch }}
